name: Snyk

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: snyk/actions/setup@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - run: snyk auth $SNYK_TOKEN
      - run: snyk code test -d
